#!/bin/bash

AUTHORS=./AUTHORS
README=./README.md
MAN=./man_1_simple_shell

if [[ -f "$AUTHORS"  ]];
then
echo "Authors_ok"

else
	echo  printf "Authors file is missing"
fi

if [[ -f "$README"  ]];
then
echo "README_ok"

else
	echo "README file is missing"
fi

if [[ -f "$MAN"  ]];
then
echo "MAN_ok"

else
	echo "MAN file is missing"
fi
