#!/bin/bash

mkdir ../pruebas

echo "/bin/ls" | /bin/sh > ../pruebas/original
echo "/bin/ls" | ./hsh > ../pruebas/yourShell
diff ../pruebas/original ../pruebas/yourShell > ../pruebas/Task3S1
rm ../pruebas/original
rm ../pruebas/yourShell
if [ -s ../pruebas/Task3S1 ]
then
	printf "error on '/bin/ls' command\n"
	rm -rf mkdir ../pruebas
else
	rm -rf ../pruebas/Task3S1
	printf "Success on '/bin/ls' command\n"
	rm -rf mkdir ../pruebas
fi
